image: node:12.14

pages:
  script:
    - npm install
    - CI=true npm test
    - CI=true npm run build --passWithNoTests
    - mv build/* $CI_PROJECT_DIR/public/
  artifacts:
    paths:
      - public
  only:
    - master